### ISSUE TITLE
Error while doing "idt Testing entry"

### ISSUE THREAD

**Issue by poisa** [chadhs/idonethis-for-alfred#18]
I get the a notification with an error when using this workflow. The error says `RUH ROH! "Testing entry" did not post.`

This is what the debug window in Alfred shows:

```
[2019-06-04 17:13:20][input.keyword] Processing output of 'action.script' with arg 'Testing entry'
[2019-06-04 17:13:20][ERROR: action.script] curl: (35) error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
[2019-06-04 17:13:20][action.script] Processing output of 'output.notification' with arg '
RUH ROH! "Testing entry" did not post.
'
```

I double checked that my api_token is correct, and that my team_id is correct as well. Tried deleting my team and using the team_id with the one I  get from the "Personal Progress Log" URL with same results.

OSX: 10.14.5
Alfred: 3.8.1 [961]
Curl info:
```
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by poisa** [comment]
A co

**Comment by poisa** [comment]
A coworker found the issue. It turns out the workflow uses `beta.idonethis.com/api/${api_version}` insted of `app.idonethis.com/api/${api_version}` as the endpoints in both scripts which is what was breaking things.

**Comment by chadhs** [comment]
@poisa thanks for figuring this out; fixed here → https://github.com/chadhs/idonethis-for-alfred/commit/3289697b3cae0b0fbb9e9025b47f47640e884434
