### ISSUE TITLE
Add "goal" feature

### ISSUE THREAD

**Issue by ladislas** [chadhs/idonethis-for-alfred#4]
Hi there!

First thank you very much for this handy workflow. I really love using it ;)

as far as I can tell, only the `idid` feature is available. would it be possible to set up `goals`?

I can help you with that if you point me in the right direction :)

**Comment by chadhs** [comment]
Great idea!  Here's a secret for you that will let you do this now.

Just start your done with [] or [ ]
Boom, now you've made a goal!
- Chad

PS
Do you think something like igoal would be a cool way to automatically prepend that for you?

**Comment by ladislas** [comment]
thanks chad! :)

for the name, `igoal` sounds good, I also though abouth `iwill`
- `idid` _check my emails_
- `iwill` _send the presentation_

**Comment by chadhs** [comment]
`iwill` sounds really good along side `idid`; great idea!  I'm not sure how soon I'll incorporate this but I'd like to add it in.  :-)
