### ISSUE TITLE
Support backticks

### ISSUE THREAD

**Issue by oalders** [chadhs/idonethis-for-alfred#7]
Hi Chad!

First off, thanks for all of your work on this.  :)

On the site itself I can say "Worked on file `foo`" and I'll see "foo" highlighted as some kind of code block.  If I try this via Alfred, whatever is inside the backticks seems to get swallowed.  That is, I don't see it via the web interface.  I haven't used the API to see what the raw done actually looks like.

**Comment by chadhs** [comment]
@oalders this is waaaaay overdue Olaf but this PR addresses your issue here and I've tested it fairly well.  https://github.com/chadhs/idonethis-for-alfred/pull/9

grab the new workflow file, enter your api and team details and you should be up and running!  ^_^

**Comment by macbikegeek** [comment]
Hi Chad,

Thanks for the workflow. It’s very helpful and works like a charm for me.

Best,

## Lee

Lee Herman
Chicago, IL 60640
macbikegeek@gmail.com
http://about.me/macbikegeek
@macbikegeek

On Jul 31, 2016, at 2:55 PM, Chad Stovern notifications@github.com wrote:

Closed #7 https://github.com/chadhs/idonethis-for-alfred/issues/7.

**Comment by chadhs** [comment]
You bet Lee!  Glad to be of help.  :-)

-- 
Chad Stovern // @chadhs

On July 31, 2016 at 9:30:22 PM, macbikegeek (notifications@github.com) wrote:

Hi Chad,

Thanks for the workflow. It’s very helpful and works like a charm for me.

Best,

## Lee

Lee Herman
Chicago, IL 60640
macbikegeek@gmail.com
http://about.me/macbikegeek
@macbikegeek

On Jul 31, 2016, at 2:55 PM, Chad Stovern notifications@github.com wrote:

Closed #7 https://github.com/chadhs/idonethis-for-alfred/issues/7.

**Comment by oalders** [comment]
@chadhs That does the trick.  Thanks so much.  👍

**Comment by chadhs** [comment]
😎👍🏼🚀
